### ISSUE TITLE
uncaught exception 'CAMetalLayerInvalid', reason: 'invalid pixel format 70'

### ISSUE THREAD

**Issue by elix22** [kakashidinho/metalangle#1]
Terminating app due to uncaught exception 'CAMetalLayerInvalid', reason: 'invalid pixel format 70'
It happen only on my MBP.

Occurs in :
https://github.com/kakashidinho/metalangle/blob/master/src/libANGLE/renderer/metal/SurfaceMtl.mm#L246

kDefaultFrameBufferColorFormatId   = angle::FormatID::B8G8R8A8_UNORM;
mColorFormat = display->getPixelFormat(kDefaultFrameBufferColorFormatId);

**mColorFormat.metalFormat = MTLPixelFormatRGBA8Unorm; 
Should be MTLPixelFormatBGRA8Unorm**

mPixelFormatTable initialisation is setting the wrong value : 
https://github.com/kakashidinho/metalangle/blob/master/src/libANGLE/renderer/metal/mtl_format_table_autogen.mm#L46

the conversion should always return MTLPixelFormatBGRA8Unorm

**Comment by kakashidinho** [comment]
This is due to inconsistent metal documents. One source says bgra8 is only supported if depth24stencil8 is supported. Yet your macbook can use it without depth24stencil8 capability.
I’m asking on Apple dev forums on this:
https://forums.developer.apple.com/thread/125104

**Comment by kakashidinho** [comment]
Until receiving clarification from Apple. Always use BGRA8Unorm for metal surface for now.

**Comment by elix22** [comment]
Sure
