### ISSUE TITLE
Debug version? 

### ISSUE THREAD

**Issue by MikeHart66** [kakashidinho/metalangle#23]
Hello and thank you for working on this framework.

I am not the smartest guy when it comes to OSX and IOS development but I am in charge to maintaining development targets for a cross platform development tool at https://www.cerberus-x.com. We have targets for OSX and IOS and use opengles 2.0 there. So MetalAngle would be an awesome solution for us.
I downloaded and build the examples which run fine. Now I am trying to integrate the metalangle.framework into our xcode project. I am confused, that the framework that was created is located in a temporary folder with the name DEBUG in its path.
Is that correct that there is no separate RELEASE version?

**Comment by kakashidinho** [comment]
Hi,
By default a Xcode project will build a debug version of the framework. If you want a release version, you can click Product -> Build For -> Profiling.
There is an alternative method, you can include my `OpenGLES.xcodeproj` framework project as children of your xcode project. Then whenever your main project is built in release mode, it will build the `MetalANGLE` framework in release mode also. In this case, please make sure the framework target is one of your main target's dependencies.

**Comment by kakashidinho** [comment]
Here are some examples on how to include `OpenGLES.xcodeproj` as your xcode project's children:
https://github.com/kakashidinho/metalangle/issues/9#issuecomment-629808879

**Comment by MikeHart66** [comment]
Thank you Kakashdinho. I will look into this.
