### ISSUE TITLE
On demand rendering missing in MGLKViewController

### ISSUE THREAD

**Issue by stephomi** [kakashidinho/metalangle#25]
I just tried metalAngle and it's awesome!
It simply worked, I'm probably going to use it in my current project.

-----------------
Minor issue 1

At the moment I had to expose the  `pause` and `resume` functions publicly to allow for on demand rendering.

Did you manage to halt the rendering loop only with `enableSetNeedsDisplay` and by using `MGLKViewController`?
With the GLKViewController, I was simply switching the `paused` attribute since `enableSetNeedsDisplay` was ignored (or automatically disabled internally).

I think `enableSetNeedsDisplay` is meant to be used with View only, not with ViewController.
But I'm not an iOS expert, so take my remark with a pinch of salt :).

https://developer.apple.com/documentation/metalkit/mtkview/1535973-paused?language=objc
https://developer.apple.com/documentation/glkit/glkviewcontroller/1620712-paused?language=objc

-----------------
Minor issue 2

In my code, I had to comment a call on `glDebugMessageCallback` because it was crashing.
```
glEnable(GL_DEBUG_OUTPUT);
glDebugMessageCallback(errorCallback, 0);
```

Maybe the problem is with my setup.
I'm using GLAD as an extension loader and it successfully report `GL_KHR_debug` as supported.

**Comment by kakashidinho** [comment]
Hi, thanks for this issue report.
1. Yes, I haven’t implemented on demand rendering with MGLKViewController yet. Thouch you might be able to do that without MGLKViewController for now. Just use only MGLKView and enableSetNeedsDisplay to NO.
2. GL_KHR_debug is not fully implemented yet. But I didn’t know it is crashing. I will need to take a look. Do you have a call stack when the crash happened?

**Comment by stephomi** [comment]
1. Great. pause/remove is working fine for me at the moment and 99% of my app is C/C++ so it was a very minor issue.

2. So... glDebugMessageCallback is 0 and I don't check for it, the fault is probably mine then, sorry!
With Angle the string extension have GL_KHR_DEBUG but it was not present with Apple OpenGL.
Basically what I'm doing is

```
if ((GLVersion.major == 3 && GLVersion.minor >= 2) || GLAD_GL_KHR_debug) {
    glEnable(GL_DEBUG_OUTPUT);
    glDebugMessageCallback(errorCallback, 0);
}
```

I assumed the presence of KHR_DEBUG implied that glDebugMessageCallback was always present but I'm not sure.

**Comment by kakashidinho** [comment]
Hi,
Just come back to `pause` & `resume` things recently. I just checked original `GLKViewController`, I don't see it has `pause` or `resume` methods either. Are you sure `GLKViewController` supports on demand rendering?

**Comment by stephomi** [comment]
Indeed `GLKViewController` doesn't have any `pause`or `resume` functions.
But it has a `paused` attribute that you can set to true after drawing the frame (drawInRect).

So what I did was basically:
- `myCtrl.paused = true` -> [myCtrl pause]
- `myCtrl.paused = false` -> [myCtrl resume]

**Comment by stephomi** [comment]
Indeed GLKViewController doesn't have any pauseor resume functions.
But it has a paused attribute that you can set to true after drawing the frame (drawInRect).

So what I did was basically:

myCtrl.paused = true -> [myCtrl pause]
myCtrl.paused = false -> [myCtrl resume]

https://developer.apple.com/documentation/glkit/glkviewcontroller/1620712-paused?language=objc

**Comment by kakashidinho** [comment]
@haxiomic has implemented the `isPaused` functionality recently https://github.com/kakashidinho/metalangle/pull/41 
So on demand rendering should be working now.

**Comment by stephomi** [comment]
Thanks, it works!
The attribute was named `paused` in GLKViewController but it's a minor thing so you can probably forget about it.

The issue can be closed.

ps: I've been using MetalAngle in the ios version of [Nomad Sculpt](https://apps.apple.com/us/app/nomad-sculpt/id1519508653#?platform=ipad), thanks again!
