### ISSUE TITLE
Compiling and running on 10.13 High Sierra

### ISSUE THREAD

**Issue by dirkpitt2050** [kakashidinho/metalangle#29]
1. On the `master` branch, OpenGLES.xcodeproj did not open with Xcode 10.1 on High Sierra due to a project version error. **Solution**: I had to edit `OpenGLES.xcodeproj/project.pbxproj` with a text editor and change `objectVersion = 52` => `objectVersion = 51`
2. Question: Do I need to run the script `scripts/run_code_generation.py` before compiling the xcodeproj? (perhaps to generate High Sierra-compatible Metal shaders, etc?)

**Comment by kakashidinho** [comment]
I don’t think you need to run code generation for macos 10.13. The code generator generated 2 versions of shader code: one for 10.13 and one for 10.14 and above. The latter won’t be used by your high sierra mac anw.

Nevertheless, I haven’t tested MetalANGLE on macos 10.13 yet. Maybe you give it a try and let me know if there is any issue.

**Comment by dirkpitt2050** [comment]
The code generators seem to work (although I only develop for macOS and so got errors when compiling shaders for iOS and tvOS).

**Comment by dirkpitt2050** [comment]
I found a blocking issue for me on 10.13:
Incorrect depth values are written to the depth buffer when glDepthRangef is used. I will write up detailed reproduction steps shortly.

**Comment by dirkpitt2050** [comment]
Example showing depth sort failing:

![image](https://user-images.githubusercontent.com/29188105/90784602-6a594680-e33c-11ea-888b-2a23e6811321.png)

Expected result:

![image](https://user-images.githubusercontent.com/29188105/90784789-983e8b00-e33c-11ea-872b-d6a7b28d0caf.png)

**Comment by kakashidinho** [comment]
This looks like depth buffer is not properly configured to me. The first picture might be rendered without any depth buffer.
FYI, If you want, you can debug metal rendering using Xcode. You can view depth buffer's values, shaders, and rendering parameters of a frame.
- First, explicitly set you project's scheme settings' GPU Frame Capture to "Metal".
![Imgur](https://i.imgur.com/DReUKQ9.png)
- Then when your app is running, you can capture a frame by clicking this "Camera" button in Xcode:
![imgur](https://imgur.com/RnWYnAN.png)
- After that, Xcode will display the frame's Metal commands on the left side.

**Comment by kakashidinho** [comment]
Ops, I didn't see your edited comments. Looks like you already did some investigations.

**Comment by kakashidinho** [comment]
Looks like the depth value was simply clamped on your 10.13 macbook instead of linear mapped.
I will create a fix by programmatically do the linear mapping in shader instead of letting Metal does it automatically in upcoming patch. Let's see if it would fix the issue on your 10.13 mac.

**Comment by dirkpitt2050** [comment]
Yes, while the mapping between MTLViewport znear and zfar <-> ndc.z seems to be undocumented, on 10.13 it seems to be something very weird like "ndc.z * far + near = depth, which would explain why every depth goes to 0.4 in my example: as every ndc.z >= 0.842 (closest cube vertex to camera), depth >= 0.842*0.4 + 0.2 >= **0.5368**.

To confirm this hypothesis, I changed the fragment shader gl_FragColor output to the following to visualize depth values:
```
gl_FragColor = vec4(gl_FragCoord.zzz, 1.0);
```
When doing this, pixels with ndc.z = 0.842 have color 137 = 137/255 = 0.537 which matches what I predicted. (BTW Very strangely, this value is not clamped to [0.2, 0.4] unlike the depth buffer values!)

Final note: Is there a possibility that this could be due to a bug in spirv-cross when translating shaders?

**Comment by kakashidinho** [comment]
We don't use spire-cross to fix up depth value. It was converted by MetalANGLE's translator. The issue might be caused by 10.13 driver's MTLViewport's near & far mapping bug which has been fixed in later OS version. The depth mapping is working fine to me at least on 10.15 when running GLES conformance tests.

I don't have any 10.13 to verify but on `gles3-temp` branch I have pushed a work-around for this by doing the linear depth mapping manually in vertex shader instead of doing it via MTLViewport's near & far mapping.
Could you pull `gles3-temp` branch and see if it fixes your issue?

**Comment by kakashidinho** [comment]
Just to explain a bit more on the depth conversion in MetalANGLE.
Previously:
1. ndc.z is converted from [-w, w] to [0, w] by internal translator (not exactly spirv-cross). A z conversion code is inserted to the result shader. **--> Done by shader.**
2. ndc.z is converted to clip.z [0, 1] by Metal internally. **--> Done by Metal internal pipeline.**
3. clip.z is converted to [near, far] by Metal internally. This step seems to have bug on your 10.13. It seems that any value larger than far will be clamped to far, similarly for near. There might not be any linear mapping like OpenGL does. However on 10.15, clip.z is linear mapped as expected by observing the conformance tests. **--> Done by Metal internal pipeline.**

In 8bfe9c70aab41a83e2766fd0af343e56a82df6fc patch, on 10.13 mac:
1. same **--> Done by shader.**
2. same **--> Done by Metal internal pipeline.**
3. clip.z is converted to [near, far] by inserting a conversion code to the translated vertex shader. Now **--> Done by shader.**

**Comment by dirkpitt2050** [comment]
Thanks for following up and sorry for the delay in feedback.. the issue is now resolved for me.

Compiling MetalANGLE (most recent master branch) and my app on Catalina 10.15 results in an executable that shows the correct glDepthMask behavior (i.e., I can see the atmosphere layer) when running on High Sierra. But the incorrect glDepthMask behavior appears in MetalANGLE compiled on 10.13. _Depending on which machine I compile_ the behavior is different. So for now, I will compile on Catalina only.

I did try the OpenGL ANGLE renderer but I am not able to get the scaling factor (Retina) correct (this is not something for you to worry about...). Everything is always twice as large as it should be even when setting view.layer.contentsScale = <scale>. But the important thing is the ANGLE Metal renderer seems to work fine now on 10.13 with the depth range fix on the master branch.

**Comment by dirkpitt2050** [comment]
The atmosphere layer issue appeared to be unrelated to depth after all. On my 10.13 machine I was testing setting default vertex shader precision to nothing (which I think means "highp"?) and this led to the atmosphere layer not rendering. I found this out by making the same shader change on my Catalina machine, which reproduced the issue. Setting the vertex shader default precision to mediump fixed the issue regardless of which OS or machine I compile or run on. I don't know why this happens, but for now the renderer I am working on works fine so I will close this issue.

**Comment by kakashidinho** [comment]
That's very weird. Actually, precision currently does not matter on Metal back-end. Would appreciate if you could find out something along the way.

**Comment by kakashidinho** [comment]
Just want to confirm something regarding the atmosphere issue. Do you use invariant keyword in your shaders? Or needing invariant capability?

**Comment by dirkpitt2050** [comment]
Nope, I do not use the invariant keyword and don't have plans to.
