### ISSUE TITLE
Crash when running MGLKitSampleApp in iOS 13.3 simulator 

### ISSUE THREAD

**Issue by mtehver** [kakashidinho/metalangle#3]
The iOS sample runs great when using older iOS simulator versions (tested with 12.0 and 11.0), but crashes in RenderUtils::initClearResources():

The crash is really a failed assert (`fragmentShader` is null). The error returned from corresponding `newFunctionWithName` is following:

Error Domain=MTLLibraryErrorDomain Code=3 "Target OS is incompatible: library was not compiled for the simulator" UserInfo={NSLocalizedDescription=Target OS is incompatible: library was not compiled for the simulator}

Am I doing anything wrong or is there a compatibility issue with latest iOS versions?

**Comment by kakashidinho** [comment]
Thanks for reporting, seems like there is a bug in simulator compatibility. Have you tried running on ios devices.

**Comment by kakashidinho** [comment]
I have fixed this issue. Please let me know if it persists.
Thanks,
