### ISSUE TITLE
Window contents scaled to half size on non-retina display

### ISSUE THREAD

**Issue by wez** [kakashidinho/metalangle#34]
Over in https://github.com/wez/wezterm I'm trying out using EGL via metalangle on macOS.
wezterm has existing EGL support on Linux and Windows, and CGL based support for macOS.

When I start wezterm+metalangle on my non-retina monitor, the UI is scaled to half size and sits in the bottom left corner of the window.
If I drag the window on my laptop's retina display, it displays correctly.

It feels like there might be an assumption about DPI/scaling somewhere in metalangle, but I'm not familiar enough to point to exactly where.

I can see that SurfaceMtl.mm looks at the layer.contentsScale to do some sizing math.  I wonder if the issue is around there?
In wezterm's CGL implementation I use `convertRectToBacking` to determine the physical pixel size and try to avoid letting macOS do any scaling of its own by using `setWantsBestResolutionOpenGLSurface`.

Do you have recommendations on how best to use metalangle with non-retina displays?

**Comment by kakashidinho** [comment]
Did your code automatically change `contentsScale` property of `CALayer` when transitioning between monitors? I presume you passed `CALayer` to ANGLE to create `EGLSurface`.
If so, MetalANGLE currently doesn’t detect that parent `CALayer`‘s scale factor has changed. It only uses parent `CALayer`‘s scale factor once during surface creation to create back buffer.

There are two ways to deal with this:
- Either don’t change EGLSurface’s CALayer’s scale factor after the EGLSurface is created, regardless of whether it is on retina or not. You can set it to 2 before creating EGLSurface but don’t change it after.
- or use `CAMetalLayer` and pass to ANGLE to create `EGLSurface`. This way MetalANGLE can detect the scaling change of `CAMetalLayer` automatically.

Hope that helps.

Implementation details notes:
- when you pass `CALayer` to create EGLSurface, MetalANGLE will internally create a `CAMetalLayer` and make it a child of the `CALayer`.
- If you pass a `CAMetalLayer`, MetalANGLE won’t create any additional layer.

**Comment by kakashidinho** [comment]
The third way is fixing MetalANGLE to auto detect that `CALayer`'s scale factor has changed. I think it should be trivial. But if you could, let me know if changing from `CALayer` to `CAMetalLayer` would solve your issue.

**Comment by wez** [comment]
What I found was that in master for ANGLE (not MetalANGLE!), the OSWindow utility class sets `contentsScale = 1.0` prior to creating the EGL surface.  If I do the same with ANGLE (which I think is using CGL under the covers by default) then I get the correct scaling when starting up on non-retina, but when I drag the window to the retina monitor, the scaling gets automatically changed to 2.0 with things in the top left corner getting zoomed in (as if the window were made half the size with the origin in the top left and then the result were stretched back out again).

If I try the same thing with MetalANGLE the behavior is similar, except that the zooming is in the bottom left when dragged to the retina display.

I tried indirectly creating `CAMetalLayer` by asking objc to find the class (I'm dynamically loading EGL so don't have a more direct way), and then calling `alloc`, `init` on it, and then assigning that as the layer and pass it through to the EGL surface initialization, but it something didn't seem to be initialized correctly, as the window appeared as though there were no view, or the view was transparent.

I'm not sure quite what to make of things; I'm tired now so I'll come at this again after some sleep.

**Comment by wez** [comment]
I just noticed the commit you pushed; I'll give that a try in the morning; thanks!

**Comment by wez** [comment]
Thanks; I can confirm that 8230df39a500e1db62fdd68d2b1e767120747c39 appears to have resolved this for me!

I've pushed a commit to wezterm that bundles that build and MetalANGLE is now its default renderer in the nightly builds, and we'll see if anybody reports problems with this!

WezTerm makes pretty basic use of shaders and GL features; are there any Metal specific issues I should keep an eye out for?

**Comment by kakashidinho** [comment]
That's good to know!
I don't think there are any issues you should be aware of. There is only one GLES3 specific issue (i.e. provoking vertex for flat varyings) right now, but I don't think your project will need it.

FYI, if you use `ios/xcode/fetchDependencies.sh` script and `ios/xcode/OpenGLES.xcodeproj`  Xcode project to build `MetalANGLE.framework`, it will be much faster than standard ANGLE building procedure (depot_tools + gclient + gn + ninja). It is not important anw since you can just include pre-compiled binaries in your project.

**Comment by wez** [comment]
Thanks for you help!
