### ISSUE TITLE
error: 'function_constant' attribute requires Metal language standard macos-metal1.2 or higher

### ISSUE THREAD

**Issue by dirkpitt2050** [kakashidinho/metalangle#36]
I have a Mac program linked to MetalAngle.framework (latest master branch) running on Catalina 10.15.7 with Xcode 12.2 on a 2019 MBP 16 and keep getting this fatal shader compile error:
```
Internal error compiling Metal shader:
Compilation failed: 

program_source:35:48: error: 'function_constant' attribute requires Metal language standard macos-metal1.2 or higher
constant bool ANGLERasterizationDisabled_tmp [[function_constant(0)]];
```

What does it mean? Do I need to upgrade to Big Sur or downgrade my Xcode?

**Comment by kakashidinho** [comment]
Looks like newer xcode broke the compilation. Maybe you try to download older version of xcode and see if the error go away.
In the mean time I will take a look at new xcode compatibility issues

**Comment by kakashidinho** [comment]
I tested on Catalina 10.15.7 with Xcode 12.2 and wasn't able to reproduce your errors. Did you change any thing in the xcode settings (for example, lower macos target version)?
This error usually comes when metal shader is compiled on macOS version below 10.13 (equivalent to metal 1.2). However, by default, my code doesn't allow metal back-end to run on macOS below 10.13. So your error encounter is strange to me.

**Comment by kakashidinho** [comment]
If possible, can you post your program here so that I can try to debug the metalangle framework used by that program?

**Comment by dirkpitt2050** [comment]
Thanks for looking into this - this was due to compiling with Qt 5.14.2 which did not set the correct Mac sdk I guess; compiling with Qt 5.15.2 fixes the issue.
