### ISSUE TITLE
EXC_BAD_ACCESS on every call to an EGL function

### ISSUE THREAD

**Issue by escamoteur** [kakashidinho/metalangle#42]
Hi,

I'm trying to add metalangle to a Pod for MacOS. I first tried to add the .framework file but wasn't able to access any of the headers of the framework. Not sure why. So I took all the library .a files and added them and flattened some of the includes so that  I finally could access egl.h from my objective c file. But when I try to call any EGL function starting with a simple
```
 void* display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
```

I get an EXC_BAD_ACCESS exception. Any idea what the problem could be? I only want to do off-screen rendering, so I don't need access to a real display.

I'm currently working on an M1 Mac with Rosetta, maybe that is a problem although I can run the MGLKitSampleApp with Rossetta.

Any help is highly appreciated :-)

**Comment by kakashidinho** [comment]
Hi,
Do you have any work-in-progress code that I can download and check? There is too few info to know what really went wrong.
