### ISSUE TITLE
Problem with different color formats 

### ISSUE THREAD

**Issue by escamoteur** [kakashidinho/metalangle#46]
Hi,

I made good progress as you can see here in the current master https://github.com/FlutterGL/flutter_web_gl

But I have a little problem, that is that the pixel format that MacOS accepts in a `CVPixelBufferCreate` is `kCVPixelFormatType_32BGRA` while all in OpenGL is RGBA which leads to rather funny colors.

Unfortunately the OpenGL ES standard doesn't contain color format conversion in `glReadPixels`  and I can't create a Renderbuffer in `BGRA` in OpenGL. Any idea how this could be easily solved?

**Comment by kakashidinho** [comment]
You can either swap the bytes on your own after `glReadPixels` or render directly to your `CVPixelBuffer` using `MetalANGLE`'s external texture extension as I mentioned last time.
I did the example for your here: https://github.com/FlutterGL/flutter_web_gl/pull/5/files

**Comment by escamoteur** [comment]
@kakashidinho This is absolutely amazing, thanks so much, that's the best possible soltuion. Swapping the pixels by hand would be probably to too slow and it seems that OpenGL es has no command to do that witht the GPU.

**Comment by kakashidinho** [comment]
You will still need to swap channels by hand if the extension is not available. This could happen if the running device is using too old version of iOS (below 11.0) or macOS (below 10.13). On those old devices, MetalANGLE fallbacks to use native OpenGL and the external texture extension is not implemented on this native OpenGL back-end.

But that’s story of another time.
