### ISSUE TITLE
Set transition style for MGLKViewController in iOS

### ISSUE THREAD

**Issue by debuggerD** [kakashidinho/metalangle#49]
Hi, thanks for great work.
I am making a game application for iOS devices with metalangle MetalANGLE framework, and need to implement animation sequence during launch.

When the app is launching, especially entered into main interface and the View created by controller which inherited MGLKViewController appears, it always shows with the sizing animation from left-top of the screen.
Also, background area not yet covered by the view has black color eventhough the background color of the view(root view of main storyboard scene) have been set as another color.

I tried to change this transition effect via setting transition style and presentation properties in XCode's storyboard editor, or even in code, but it doesn't work.

Is it possible to change or turn off transition animations of MGLKViewController's presentation?
I look forward to hearing from you a way to do it.

**Comment by kakashidinho** [comment]
Ops sorry, I was too busy with my works that I missed this issue. Will take a look.
Thanks for the reporting.

**Comment by jkazma-logisk** [comment]
Seconded. It kind of breaks the seamless transition between the launch screen and the app and I don't think Apple would like that.
