### ISSUE TITLE
Retain cycle between MGLContext and MGLSharegroup

### ISSUE THREAD

**Issue by aab29** [kakashidinho/metalangle#50]
First of all, thank you @kakashidinho for creating such a useful library!  Your work is very impressive.  👏

I'm working on an application that creates an `MGLKViewController` to display a game and later destroys it.  I noticed that after the view controller itself has been destroyed, the `MGLContext` object it was using is leaked.  In my case, that prevented all of the memory allocated for the game's textures from being released.

I looked into the issue and figured out that there is a [retain cycle](https://stackoverflow.com/questions/19892245/understanding-retain-cycle-in-depth) between `MGLContext` and the `MGLSharegroup` associated with it.  I was able to fix the problem by adding `weak` to the `firstContext` property of `MGLSharegroup`.

```objective-c
// MGLSharegroup implementation
@interface MGLSharegroup ()
@property(atomic, weak) MGLContext *firstContext;
@end
```

After I made the reference `weak`, both the `MGLContext` and its `MGLSharegroup` called `dealloc`, and the game's texture memory was released properly.  I'm not sure if there is any reason why `firstContext` needs to be a strong reference, however.

Please let me know if I'm misunderstanding anything about the library, or if I can help in any way.  Thank you!

**Comment by kakashidinho** [comment]
Thanks for reporting this bug. Yes, it should be a weak reference.
Could you create a PR for the fix you already created if you don't mind?

**Comment by aab29** [comment]
Of course!  I'll submit a PR soon.  Thanks for your quick response!  🙂
