### ISSUE TITLE
crash on iOS

### ISSUE THREAD

**Issue by wasabia** [kakashidinho/metalangle#52]
maybe when call linkProgram happen

```
Runner(4953,0x16c25f000) malloc: Heap corruption detected, free list is damaged at 0x28130d1c0
*** Incorrect guard value: 63956752584960
Runner(4953,0x16c25f000) malloc: *** set a breakpoint in malloc_error_break to debug
Runner(4953,0x16c25f000) malloc: Heap corruption detected, free list is damaged at 0x28130d1c0
*** Incorrect guard value: 63956752584960
```

<img width="967" alt="" src="https://user-images.githubusercontent.com/1768228/116339907-d9af0080-a810-11eb-9c86-24efdae0513e.png">

**Comment by kakashidinho** [comment]
Could you provide a small example code that causes this crash?
Without it i cannot reproduce the crash.
