### ISSUE TITLE
[question] Failed To call eglInitialize()

### ISSUE THREAD

**Issue by petr-pokorny-1** [kakashidinho/metalangle#55]
We have successfully used MetalAngle in [MapLibre iOS library](https://github.com/maplibre/maplibre-gl-native). We have problem with our unit tests which are using MGLKit - if we run them locally on macos, they pass but of we run them on GitHub macos runner (tried 10.15 and 11.0) they [fail with exception](https://github.com/maplibre/maplibre-gl-native/runs/2487643668?check_suite_focus=true#step:12:1551) `Failed To call eglInitialize()` - the related code in MetalAngle is [here](https://github.com/kakashidinho/metalangle/blob/1ce2a4ff587cd7d1dd0a6a6259fe78bb5d3bc95e/ios/xcode/MGLKit/MGLDisplay.mm#L37)

Is this a known problem? Any hints what needs to be done?

**Comment by kakashidinho** [comment]
afaik, github’s macos bot doesn’t support metal (metal needs real gpu) so you cannot initialize MetalANGLE on the bot.
Unless Apple implement software rasterizer for their metal API.
But i might try to fallback to use OpenGL internally in MetalANGLE if you need rendering unit tests on CI server.

**Comment by petr-pokorny-1** [comment]
I set up a runner on my Mac and tried to launch GitHub action workflow (with unit tests) using this runner but I am getting the same exception. It is interesting because when I run the same tests from Xcode, no exception is thrown. I will try to find more information.

**Comment by petr-pokorny-1** [comment]
My apologies- I found error in my settings. When i fixed it and run it again, everything worked correctly on self-hosted runner. That confirms github bots dont have gpu. We will use self-hosted runner as a workaround. Thanks for help!
