### ISSUE TITLE
No member named 'force_native_arrays' in 'spirv_cross::CompilerMSL::Options'

### ISSUE THREAD

**Issue by Cyp** [kakashidinho/metalangle#9]
Not sure if I did something wrong somewhere, but I'm getting
`OpenGLES/angle_metal_backend/mtl_glslang_utils.mm:796: No member named 'force_native_arrays' in 'spirv_cross::CompilerMSL::Options'`.

Happens in the master branch since 252f9993d1f040992f724929cb42961c2a7079aa.

**Comment by kakashidinho** [comment]
Hi, third party libraries have been updated. Pls run “ios/xcode/fetchDependencies.sh”
or “gclient sync”

**Comment by Cyp** [comment]
That seems to have worked, thanks. Sorry about the noise, then.

**Comment by Cyp** [comment]
Now got it to run, thanks.

Got some "Failed to present framebuffer" exceptions. Removing a call I had to `MGLContext.setCurrent(context)` from `mglkView:view:rect` seems to help, even though it seems to be setting the context to what it already was. Is calling `setCurrent` from the render function forbidden or is it a bug?

The `gles2` branch seems to mostly work, but with the  `gles3` branch, I get:
```
FATAL: convertVertexBuffer(851):  ! Assert failed in convertVertexBuffer
    (src/libANGLE/renderer/metal/VertexArrayMtl.mm:851): (conversion->data.getAlignment() % convertedAngleFormat.pixelBytes) == 0
```
I think conversion->data.getAlignment() is 6, which isn't a power of two. The problem seems to be triggered by doing `glVertexAttribPointer(1, 3, GL_SHORT, false, 32, (void *)8);`, and changing the `3` to a `4` is a workaround.

**Comment by kakashidinho** [comment]
The GL_SHORT vertex conversion crash should be fixed in latest master version. Can you try again?

**Comment by Cyp** [comment]
Thanks, both GL_SHORT and (redundantly) setting the context are working now for me.

By the way, is there a list somewhere of things that cause it to need conversion? And if so, is the list highly specific to Metal/Apple hardware, or general to a lot of hardware?

**Comment by kakashidinho** [comment]
The conversion is needed because Metal requires that vertex attribute’s offset must be multiples of attribute’s sise. This is explicitly stated in Metal API documents https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515829-setvertexbuffer?language=objc. For example GL_SHORTx3 must have offset=0 or 6 or 12, etc. If this rule is not respected, metal validation layer will complain and crash the app.
This is just one of the rules anw, the other one is that vertex stride must be mutiples of 4.

**Comment by Cyp** [comment]
Thanks —- however, if making the offset of the GL_SHORT×3 be 18 (a multiple of 6, but not of 4), I get a crash in a `[encoder drawIndexedPrimitives:MTPPrimitiveTypeTriangle indexCount:168 indexType:MTLIndexTypeUint16 indexBuffer:indexBuffer indexBufferOffset:28216]` call:

validateFunctionArguments:3481: failed assertion `Vertex Function(main0): the offset into the buffer vertexBuffer.1 that is bound at buffer index 1 must be a multiple of 4 but was set to 18.

**Comment by kakashidinho** [comment]
Sight, this is new. It seems setVertexBuffer expects the offset to be multiple of 4 in addition to being multiple of attribute size also (their setVertexBuffer doc doesn’t even mention this)

**Comment by kakashidinho** [comment]
Fixed in f6516e03. Thanks for the report again.

**Comment by Cyp** [comment]
Thanks.

Testing by commenting out the ASSERT at VertexArratMtl.mm:387 and making needConversion always be false, I'm only seeing crashes in Metal when the offset isn't 4-byte aligned, for any data type I tested.

In particular, GL_SHORT×3 with an offset of 8 worked fine with conversion disabled. I think any non-power-of-2 alignment requirement is unusual.

I think the alignment requirement comes from the GL_SHORT, not from the ×3 (with a minimum alignment requirement of 4), so I'd expect GL_DOUBLE×3 or GL_INT64×3 to need 8-byte alignment, if they were supported.

**Comment by kakashidinho** [comment]
Their doc mentions "align the offset to the data type consumed by the vertex function (which is always less than or equal to 16 bytes)." There is no scalar type that has size=16 bytes supported by metal atm, so most likely this statement implies the vector type (i.e. scalarx4 for example).

I think this is typical mismatch between their docs and validation layer's behaviors.

**Comment by Cyp** [comment]
Don't know whether it's applicable, but https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf section 2.2 lists alignments for vector types and says `short3` has size 8 and alignment 8. It also says `packed_short3` has size 6 and alignment 2. Weirdly, neither agree with the alignment of 4 which empirically seems to be what's actually needed. And it claims `long4` has an alignment of 32 which is more than the 16 maximum.

**Comment by kakashidinho** [comment]
long is not accessible as vertex attribute atm. It might be used inside shader though.
Also long type is only added recently, most likely Apple don't bother to update their API doc.

**Comment by kakashidinho** [comment]
FYI, there is a way for MetalANGLE to support any vertex offset, stride by tinkering the back-end metal compiler to use byte pointer for every vertex attribute in shader, then insert relevant casting, conversion code to the the shader when information about the vertex specifications is known at runtime (I'm thinking about doing this at some point).
I'm not sure it's worth the hassle though. The current way of conversion actually happens only once whenever the vertex buffer's data is changed. Static buffers should have their data converted only once during the lifetime of app.

**Comment by Cyp** [comment]
I seem to be running into a weird issue with stencil buffers. On the simulator, it seems to work. On an actual device, I'm seeing inconsistent behaviour — in one case nothing drawn except for transparent objects. Not sure exactly what triggers it.

My vertex attributes are 4-byte-aligned, and I've disabled the vertex buffer conversion code locally, but I assume that that wouldn't somehow trigger the stencil buffer issue.

```c++
glClear(GL_STENCIL_BUFFER_BIT);
glEnable(GL_STENCIL_TEST);
glStencilFunc(GL_EQUAL, 0, 2);  // Should always pass, since the stencil buffer is clear.
// Now opaque (with blending disabled) objects aren't rendered on the device, only in the
// emulator.

glClear(GL_STENCIL_BUFFER_BIT);
glEnable(GL_STENCIL_TEST);
glStencilFunc(GL_LEQUAL, 1, 1);  // Should always pass, no matter what is in the stencil
                                 // buffer.
// Same problem as above

glClear(GL_STENCIL_BUFFER_BIT);
glEnable(GL_STENCIL_TEST);
glStencilFunc(GL_ALWAYS, 0, 1);  // Always passes.
// Seems to work. Not sure whether or not the stencil buffer gets correctly written.
```

By the way, is there an easy way to switch between from device/emulator to emulator/device in a project, without having to delete MetalANGLE.framework from the project, and re-add a device/emulator build of the framework.

**Comment by kakashidinho** [comment]
Is it possible to share your sample code somewhere? perhaps a github repo?

Also, pls try to revert to old conversation code if it works, unsupported offset could cause undefined values leading to undefined stencil values.

**Comment by kakashidinho** [comment]
Btw to avoid switching framework versions, you can try to use lipo to merge emulator and device version of metalangle into one single framework.

The other way is using metalangle xcode project as child project of your project. Xcode can automatically switch framework version in this case.

**Comment by kakashidinho** [comment]
Update: I attempted to use stencil on iOS today and indeed it doesn't work as expected. This is very weird, I even debug using metal frame capture tool, but didn't find any bug, however the stencil on Metal side just doesn't work. It seems like driver bug to me, or there is some things about how stencil work on iOS which I haven't fully understood yet.

**Comment by kakashidinho** [comment]
I also tried to run sample metal app provided by Xcode template, and set stencil compare function to MTLCompareFunctionEqual, it also didn't draw anything on the device's screen. Very weird.
However, setting compare function to MTLCompareFunctionGreaterEqual works.

**Comment by kakashidinho** [comment]
I made a work-around fix for the driver issue here 4cda8f7d82021dd6fc411f353a5d4aae9042a186. Let me know if stencil works for you now.

**Comment by Cyp** [comment]
Thanks, it seems to be working better now, at least with GL_EQUAL (which is the main one).

Now works correctly: `GL_EQUAL`, `GL_ALWAYS`, `GL_NEVER`.
Always fails stencil test (false negatives), ignoring ref/mask: `GL_LEQUAL`, `GL_LESS`.
Always passes stencil test (false positives), ignoring ref/mask: `GL_GEQUAL`, `GL_GREATER`.
Forgot to test: `GL_NEQUAL`.

It seems as if it's somehow reading the stencil buffer values as numerically greater than any other value.

**Comment by kakashidinho** [comment]
All of compare functions work on my iphone.
For example:
```
// 1 & 0x1 = 1 > 2 & 0x1 = 0 -> stencil test passed
glClearStencil(2);
glClear(GL_STENCIL_BUFFER_BIT);
glEnable(GL_STENCIL_TEST);
glStencilFunc(GL_GREATER, 1, 0x1);
```
```
// 1 & 0x1 > 0 & 0x1 -> passed
glClearStencil(0);
glClear(GL_STENCIL_BUFFER_BIT);
glEnable(GL_STENCIL_TEST);
glStencilFunc(GL_GREATER, 1, 0x1);
```
```
// 1 & 0x3 > 2 & 0x3 -> failed stencil test
glClearStencil(2);
glClear(GL_STENCIL_BUFFER_BIT);
glEnable(GL_STENCIL_TEST);
glStencilFunc(GL_GREATER, 1, 0x3);
```
```
// 1 & 0x3 > 0 & 0x3 -> passed
glClearStencil(0);
glClear(GL_STENCIL_BUFFER_BIT);
glEnable(GL_STENCIL_TEST);
glStencilFunc(GL_GREATER, 1, 0x3);
```
Previously, the default stencil ref on IOS device is 255 (as oppose to zero as stated in the API doc) as observed from my frame capture, my code assumed the ref was already zero thus skipping setting the ref value. Hence the tests before recent commit all use 255 as ref value.

**Comment by Cyp** [comment]
Ok — sorry, it seems that the remaining issue was probably just me being confused. I was reading `glStencilFunc(GL_LESS, 42, 0xff)` as `buffer value < 42`, when it apparently means `42 < buffer value`, and only tested with nonzero ref and zero buffer values today.

**Comment by Cyp** [comment]
By the way, how do I add a child project? I can't find any documentation for it that actually works.

If dragging OpenGLES.xcodeproj onto the project, it looks as if it's there, but building fails with `'MGLKit.h' file not found`. Searching the drive for 'MGLKit.h' finds it in a subdirectory of the pseudorandomly-named directory Library/Developer/Xcode/DerivedData/OpenGLES-bt*vm, so I can't even add it to the include path.

**Comment by kakashidinho** [comment]
`MGLKit.h` is at `<MetalANGLE root folder>/ios/xcode/MGLKit/MGLKit.h`. Can you just include its folder in the headers search path?
Actually, I believe if you include `OpenGLES.xcodeproj` as child project, and link your target against the `MetalANGLE.framework`, you can just use `#include <MetalANGLE/MGLKit.h>` (note the `MetalANGLE/` prefix). There is no need to set any search path, it will be automatically deduced by xcode. I might be wrong though.

Examples of `OpenGLES.xcodeproj` as child project:
- MetalANGLE's `MGLKitSamples.xcodeproj` basically uses `OpenGLES.xcodeproj` as child project, I used "Add existing file ..." and choosed `OpenGLES.xcodeproj` to make it a child project.
- My other repo https://github.com/kakashidinho/irrlicht also includes `OpenGLES.xcodeproj` as child project of Irrlitcht engine's `Irrlitcht.xcodeproj`.

**Comment by Cyp** [comment]
Thanks — after adding MetalANGLE to project settings/Build Phases/Dependencies and the library to project settings/Build Phases/Link Binary With Libraries, and adding the `MetalAngle/` prefix to the `#include`, it seems to be working.
